language: java
install: true
sudo: false

# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# Travis now defaults to Trusty, which is missing openjdk6.
# dist: precise

install:
  # install maven 3.2.5
  - bash .travis.install-maven.sh "${MVN_VERSION}" "${HOME}/mvn-home"
  - export M2_HOME=${HOME}/mvn-home
  - export PATH=${HOME}/mvn-home/bin:${PATH}
  - mvn -version

addons:
  apt:
    packages:
      - fluxbox

cache:
 directories:
   - $HOME/.m2/repository

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - fluxbox &> ~/fluxbox.log &
  - sleep 3

jdk:
  - oraclejdk8

matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
      env: MVN_VERSION="3.2.5"
    - addons:
        apt:
          packages:
            - openjdk-7-jdk
      jdk: openjdk7
      env: MVN_VERSION="3.3.9"
    - jdk: oraclejdk8
      env: MVN_VERSION="3.3.9"
    - jdk: oraclejdk9
      env: MVN_VERSION="3.3.9"

env:
  global:
    - JAVA_OPTS="-Djava.awt.headless=false"

script:
  - mvn -U clean verify
  - mvn verify -Pwith-gui-tests

notifications:
  email: false
