language: java
install: true
sudo: false

install:
  # install maven 3.2.5
  - bash .travis.install-maven.sh "3.2.5" "${HOME}/mvn-home"
  - export M2_HOME=${HOME}/mvn-home
  - export PATH=${HOME}/mvn-home/bin:${PATH}
  - mvn -version

addons:
  apt:
    packages:
      - openjdk-6-jdk
      - openjdk-7-jdk
      - fluxbox

cache:
 directories:
   - $HOME/.m2/repository

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - fluxbox &> ~/fluxbox.log &
  - sleep 3

jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  - oraclejdk8

env:
  global:
    - JAVA_OPTS="-Djava.awt.headless=false"

script:
  - mvn -U clean verify
  - mvn verify -Pwith-gui-tests

notifications:
  email: false
